name: Testing
on: 
  pull_request: 
    branches: 
      - main
  workflow_dispatch:
jobs: 
  Liquibase_Job:
    runs-on: windows-latest
    steps:
      - name: Clone Repo
        uses: actions/checkout@v3
      - name: Configure snowflake variables & run mvn liquibase update
        run: |
          $env:JAVA_HOME = $env:JAVA_HOME_11_X64
          $env:SNOWFLAKE_ENV_ID = "QUALITY"
          $env:SNOWFLAKE_ACCOUNT = "AHVINWU.MHB38642"
          $env:SNOWFLAKE_WAREHOUSE = "${{ secrets.SNOWFLAKE_WAREHOUSE }}"
          $env:SNOWFLAKE_ROLE = "SYSADMIN"
          $env:SNOWFLAKE_USER = "SURESHYADAV"
          $env:SNOWFLAKE_PASSWORD = "Suresh@18"
          mvn -version
          mvn install 
          mvn liquibase:update
