name: Testing
on: 
  workflow_dispatch:
jobs: 
  Liquibase_Job:
    runs-on: windows-latest
    steps:
      - name: Clone Repo
        uses: actions/checkout@v3
      - name: Configure snowflake variables & run mvn liquibase update
        run: |
          $env:SNOWFLAKE_ENV_ID = "QUALITY"
          $env:SNOWFLAKE_ACCOUNT = "tdunaim-jq77831"
          $env:SNOWFLAKE_WAREHOUSE = "COMPUTE_WH"
          $env:SNOWFLAKE_ROLE = "ACCOUNTADMIN"
          $env:SNOWFLAKE_USER = "RAJU_EARLAPALLY"
          $env:SNOWFLAKE_PASSWORD = "Welcome@123"
          $env:SCHEMA_NAME = "DEV"
          mvn -version
          mvn install 
          mvn liquibase:update
