name: Testing
on: 
  workflow_dispatch:
jobs: 
  Liquibase_Job:
    runs-on: windows-latest
    steps:
      - name: Clone Repo
        uses: actions/checkout@v3
      - name: Configure snowflake variables & run mvn liquibase update
        run: |
          $env:JAVA_HOME = $env:JAVA_HOME_11_X64
          $env:SNOWFLAKE_ENV_ID = "QUALITY"
          $env:SNOWFLAKE_ACCOUNT = "ahvinwu-mhb38642"
          $env:SNOWFLAKE_WAREHOUSE = "COMPUTE_WH"
          $env:SNOWFLAKE_ROLE = "SYSADMIN"
          $env:SNOWFLAKE_USER = "SURESHYADAV"
          $env:SNOWFLAKE_PASSWORD = "Suresh@18"
          $env:SCHEMA_NAME = "DEV"
          mvn -version
          mvn install 
          mvn liquibase:update
