name: SnowflakeLiquibaseDeployment
on: 
  pull_request: 
    branches: 
      - main
  workflow_dispatch:
jobs: 
  Liquibase_Job:
    runs-on: windows-latest
    steps:
      - name: Clone Repo
        uses: actions/checkout@v3
      - name: Write private key to file
        run: |
          $keyPath = "$env:GITHUB_WORKSPACE\snowflake_rsa_key.p8"
          Set-Content -Path $keyPath -Value "${{ secrets.SNOWFLAKE_PRIVATE_KEY }}" -Encoding ascii
          $env:SNOWFLAKE_PRIVATE_KEY_PATH = $keyPath
          echo "Private key written to: $keyPath"
      - name: Configure snowflake variables & run mvn liquibase update
        run: |
          $env:SNOWFLAKE_ENV_ID = "QUAL"
          $env:SNOWFLAKE_ACCOUNT = "XDAAIJY-FI41763"
          $env:SNOWFLAKE_WAREHOUSE = "${{secrets.SNOWFLAKE_WAREHOUSE}}"
          $env:SNOWFLAKE_ROLE = "${{secrets.SNOWFLAKE_ROLE}}"
          $env:SNOWFLAKE_USER = "${{secrets.SNOWFLAKE_USER}}"
          $env:SNOWFLAKE_PASSWORD = "${{secrets.SNOWFLAKE_PASSWORD}}"
          $env:PRIVATE_KEY_PASSPHRASE = "${{ secrets.SNOWFLAKE_PRIVATE_KEY_PASSPHRASE }}"
          mvn -version
          mvn install
          mvn liquibase:update `
            -Dnet.snowflake.jdbc.privateKeyFile="$env:GITHUB_WORKSPACE\snowflake_rsa_key.p8" `
            -Dnet.snowflake.jdbc.privateKeyFilePwd="$env:PRIVATE_KEY_PASSPHRASE"
