name: SnowflakeLiquibaseDeployment
on: 
  pull_request: 
    branches: 
      - main
  workflow_dispatch:
jobs: 
  Liquibase_Job:
    runs-on: windows-latest
    steps:
      - name: Clone Repo
        uses: actions/checkout@v3
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '11'  
          distribution: 'adopt'
      - name: Configure snowflake variables & run mvn liquibase update
        run: |
          $env:SNOWFLAKE_ENV_ID = "QUALITY"
          $env:SNOWFLAKE_EXT_STG_ENV = "DEV"
          $env:SNOWFLAKE_ACCOUNT = "cupueci-lmb72269"
          $env:SNOWFLAKE_WAREHOUSE = "COMPUTE_WH"
          $env:SNOWFLAKE_ROLE = "ACCOUNTADMIN"
          $env:SNOWFLAKE_USER = "SureshYadav"
          $env:SNOWFLAKE_PASSWORD = "Welcome@123"
          mvn -version
          mvn install 
          mvn -e liquibase:update
